# Generated by Django 4.1.4 on 2023-01-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='teacher', max_length=10)),
                ('salary', models.CharField(default='2000', max_length=2)),
            ],
        ),
    ]
